In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import networkx as nx
from subprocess import check_output
%matplotlib inline

In [2]:
df=pd.read_csv('C:\\Users\\p860n111\\Desktop\\data science\\Hw2\\Shakespeare_data.csv')

In [3]:
# to see the total number of columns in the dataset.
df = df.dropna()
df.columns

Index(['Dataline', 'Play', 'PlayerLinenumber', 'ActSceneLine', 'Player',
       'PlayerLine'],
      dtype='object')

In [4]:
#to find the total number of unique play
print("Number of plays are: " + str(df['Play'].nunique()))

Number of plays are: 36

In [5]:
# to calculate the total words in each PlayerLine cell entry
df['NoOfWordsInPlayerLine'] = df.PlayerLine.apply(lambda x: len(str(x).split(' ')))

In [6]:
df

,Dataline,Play,PlayerLinenumber,ActSceneLine,Player,PlayerLine,NoOfWordsInPlayerLine
0,1,Henry IV,NaN,NaN,NaN,ACT I,2
1,2,Henry IV,NaN,NaN,NaN,SCENE I. London. The palace.,5
2,3,Henry IV,NaN,NaN,NaN,"Enter KING HENRY, LORD JOHN OF LANCASTER, the ...",16
3,4,Henry IV,1.0,1.1.1,KING HENRY IV,"So shaken as we are, so wan with care,",9
4,5,Henry IV,1.0,1.1.2,KING HENRY IV,"Find we a time for frighted peace to pant,",9
5,6,Henry IV,1.0,1.1.3,KING HENRY IV,And breathe short-winded accents of new broils,7
6,7,Henry IV,1.0,1.1.4,KING HENRY IV,To be commenced in strands afar remote.,7
7,8,Henry IV,1.0,1.1.5,KING HENRY IV,No more the thirsty entrance of this soil,8
8,9,Henry IV,1.0,1.1.6,KING HENRY IV,Shall daub her lips with her own children's bl...,9
9,10,Henry IV,1.0,1.1.7,KING HENRY IV,"Nor more shall trenching war channel her fields,",8
10,11,Henry IV,1.0,1.1.8,KING HENRY IV,Nor bruise her flowerets with the armed hoofs,8
11,12,Henry IV,1.0,1.1.9,KING HENRY IV,"Of hostile paces: those opposed eyes,",6
12,13,Henry IV,1.0,1.1.10,KING HENRY IV,"Which, like the meteors of a troubled heaven,",8
13,14,Henry IV,1.0,1.1.11,KING HENRY IV,"All of one nature, of one substance bred,",8
14,15,Henry IV,1.0,1.1.12,KING HENRY IV,Did lately meet in the intestine shock,7
15,16,Henry IV,1.0,1.1.13,KING HENRY IV,And furious close of civil butchery,6
16,17,Henry IV,1.0,1.1.14,KING HENRY IV,"Shall now, in mutual well-beseeming ranks,",6
17,18,Henry IV,1.0,1.1.15,KING HENRY IV,March all one way and be no more opposed,9
18,19,Henry IV,1.0,1.1.16,KING HENRY IV,"Against acquaintance, kindred and allies:",5
19,20,Henry IV,1.0,1.1.17,KING HENRY IV,"The edge of war, like an ill-sheathed knife,",8
20,21,Henry IV,1.0,1.1.18,KING HENRY IV,"No more shall cut his master. Therefore, friends,",8
21,22,Henry IV,1.0,1.1.19,KING HENRY IV,"As far as to the sepulchre of Christ,",8
22,23,Henry IV,1.0,1.1.20,KING HENRY IV,"Whose soldier now, under whose blessed cross",7
23,24,Henry IV,1.0,1.1.21,KING HENRY IV,"We are impressed and engaged to fight,",7
24,25,Henry IV,1.0,1.1.22,KING HENRY IV,"Forthwith a power of English shall we levy,",8
25,26,Henry IV,1.0,1.1.23,KING HENRY IV,Whose arms were moulded in their mothers' womb,8
26,27,Henry IV,1.0,1.1.24,KING HENRY IV,To chase these pagans in those holy fields,8
27,28,Henry IV,1.0,1.1.25,KING HENRY IV,Over whose acres walk'd those blessed feet,7
28,29,Henry IV,1.0,1.1.26,KING HENRY IV,Which fourteen hundred years ago were nail'd,7
29,30,Henry IV,1.0,1.1.27,KING HENRY IV,For our advantage on the bitter cross.,7
...,...,...,...,...,...,...,...
111366,111367,A Winters Tale,37.0,5.3.155,PAULINA,"There's time enough for that,",5
111367,111368,A Winters Tale,37.0,5.3.156,PAULINA,Lest they desire upon this push to trouble,8
111368,111369,A Winters Tale,37.0,5.3.157,PAULINA,"Your joys with like relation. Go together,",7
111369,111370,A Winters Tale,37.0,5.3.158,PAULINA,"You precious winners all, your exultation",6
111370,111371,A Winters Tale,37.0,5.3.159,PAULINA,"Partake to every one. I, an old turtle,",8
111371,111372,A Winters Tale,37.0,5.3.160,PAULINA,Will wing me to some wither'd bough and there,9
111372,111373,A Winters Tale,37.0,5.3.161,PAULINA,"My mate, that's never to be found again,",8
111373,111374,A Winters Tale,37.0,5.3.162,PAULINA,Lament till I am lost.,5
111374,111375,A Winters Tale,38.0,5.3.163,LEONTES,"O, peace, Paulina!",3
111375,111376,A Winters Tale,38.0,5.3.164,LEONTES,"Thou shouldst a husband take by my consent,",8
111376,111377,A Winters Tale,38.0,5.3.165,LEONTES,"As I by thine a wife: this is a match,",10
111377,111378,A Winters Tale,38.0,5.3.166,LEONTES,"And made between's by vows. Thou hast found mine,",9
111378,111379,A Winters Tale,38.0,5.3.167,LEONTES,"But how, is to be question'd, for I saw her,",10
111379,111380,A Winters Tale,38.0,5.3.168,LEONTES,"As I thought, dead, and have in vain said many",10
111380,111381,A Winters Tale,38.0,5.3.169,LEONTES,A prayer upon her grave. I'll not seek far--,9
111381,111382,A Winters Tale,38.0,5.3.170,LEONTES,"For him, I partly know his mind--to find thee",9
111382,111383,A Winters Tale,38.0,5.3.171,LEONTES,"An honourable husband. Come, Camillo,",5
111383,111384,A Winters Tale,38.0,5.3.172,LEONTES,"And take her by the hand, whose worth and honesty",10
111384,111385,A Winters Tale,38.0,5.3.173,LEONTES,Is richly noted and here justified,6
111385,111386,A Winters Tale,38.0,5.3.174,LEONTES,"By us, a pair of kings. Let's from this place.",10
111386,111387,A Winters Tale,38.0,5.3.175,LEONTES,"What! look upon my brother: both your pardons,",8
111387,111388,A Winters Tale,38.0,5.3.176,LEONTES,That e'er I put between your holy looks,8
111388,111389,A Winters Tale,38.0,5.3.177,LEONTES,"My ill suspicion. This is your son-in-law,",7
111389,111390,A Winters Tale,38.0,5.3.178,LEONTES,"And son unto the king, who, heavens directing,",8
111390,111391,A Winters Tale,38.0,5.3.179,LEONTES,"Is troth-plight to your daughter. Good Paulina,",7
111391,111392,A Winters Tale,38.0,5.3.180,LEONTES,"Lead us from hence, where we may leisurely",8
111392,111393,A Winters Tale,38.0,5.3.181,LEONTES,Each one demand an answer to his part,8
111393,111394,A Winters Tale,38.0,5.3.182,LEONTES,Perform'd in this wide gap of time since first,9
111394,111395,A Winters Tale,38.0,5.3.183,LEONTES,We were dissever'd: hastily lead away.,6
111395,111396,A Winters Tale,38.0,NaN,LEONTES,Exeunt,1

In [6]:
df.dtypes

Dataline                   int64
Play                      object
PlayerLinenumber         float64
ActSceneLine              object
Player                    object
PlayerLine                object
NoOfWordsInPlayerLine      int64
dtype: object

In [7]:
df["Play"] = df["Play"].astype('category')
df.dtypes
df["Play_cat"] = df["Play"].cat.codes
df.head()

,Dataline,Play,PlayerLinenumber,ActSceneLine,Player,PlayerLine,NoOfWordsInPlayerLine,Play_cat
3,4,Henry IV,1.0,1.1.1,KING HENRY IV,"So shaken as we are, so wan with care,",9,9
4,5,Henry IV,1.0,1.1.2,KING HENRY IV,"Find we a time for frighted peace to pant,",9,9
5,6,Henry IV,1.0,1.1.3,KING HENRY IV,And breathe short-winded accents of new broils,7,9
6,7,Henry IV,1.0,1.1.4,KING HENRY IV,To be commenced in strands afar remote.,7,9
7,8,Henry IV,1.0,1.1.5,KING HENRY IV,No more the thirsty entrance of this soil,8,9

In [8]:
df.dtypes

Dataline                    int64
Play                     category
PlayerLinenumber          float64
ActSceneLine               object
Player                     object
PlayerLine                 object
NoOfWordsInPlayerLine       int64
Play_cat                     int8
dtype: object

In [9]:
df["PlayerLinenumber"] = df["PlayerLinenumber"].astype('category')
df.dtypes
df["PlayerLinenumber_cat"] = df["PlayerLinenumber"].cat.codes
df.head()
df["ActSceneLine"] = df["ActSceneLine"].astype('category')
df.dtypes
df["ActSceneLine_cat"] = df["ActSceneLine"].cat.codes
df.head()
df["Player"] = df["Player"].astype('category')
df.dtypes
df["Player_cat"] = df["Player"].cat.codes
df.head()

,Dataline,Play,PlayerLinenumber,ActSceneLine,Player,PlayerLine,NoOfWordsInPlayerLine,Play_cat,PlayerLinenumber_cat,ActSceneLine_cat,Player_cat
3,4,Henry IV,1.0,1.1.1,KING HENRY IV,"So shaken as we are, so wan with care,",9,9,0,324,457
4,5,Henry IV,1.0,1.1.2,KING HENRY IV,"Find we a time for frighted peace to pant,",9,9,0,435,457
5,6,Henry IV,1.0,1.1.3,KING HENRY IV,And breathe short-winded accents of new broils,7,9,0,546,457
6,7,Henry IV,1.0,1.1.4,KING HENRY IV,To be commenced in strands afar remote.,7,9,0,657,457
7,8,Henry IV,1.0,1.1.5,KING HENRY IV,No more the thirsty entrance of this soil,8,9,0,768,457

In [10]:
df.dtypes

Dataline                    int64
Play                     category
PlayerLinenumber         category
ActSceneLine             category
Player                   category
PlayerLine                 object
NoOfWordsInPlayerLine       int64
Play_cat                     int8
PlayerLinenumber_cat        int16
ActSceneLine_cat            int16
Player_cat                  int16
dtype: object

In [11]:
df["PlayerLine"] = df["PlayerLine"].astype('category')
df.dtypes
df["PlayerLine_cat"] = df["PlayerLine"].cat.codes
df.head()

,Dataline,Play,PlayerLinenumber,ActSceneLine,Player,PlayerLine,NoOfWordsInPlayerLine,Play_cat,PlayerLinenumber_cat,ActSceneLine_cat,Player_cat,PlayerLine_cat
3,4,Henry IV,1.0,1.1.1,KING HENRY IV,"So shaken as we are, so wan with care,",9,9,0,324,457,60240
4,5,Henry IV,1.0,1.1.2,KING HENRY IV,"Find we a time for frighted peace to pant,",9,9,0,435,457,23568
5,6,Henry IV,1.0,1.1.3,KING HENRY IV,And breathe short-winded accents of new broils,7,9,0,546,457,4998
6,7,Henry IV,1.0,1.1.4,KING HENRY IV,To be commenced in strands afar remote.,7,9,0,657,457,73793
7,8,Henry IV,1.0,1.1.5,KING HENRY IV,No more the thirsty entrance of this soil,8,9,0,768,457,48893

In [12]:
df.dtypes

Dataline                    int64
Play                     category
PlayerLinenumber         category
ActSceneLine             category
Player                   category
PlayerLine               category
NoOfWordsInPlayerLine       int64
Play_cat                     int8
PlayerLinenumber_cat        int16
ActSceneLine_cat            int16
Player_cat                  int16
PlayerLine_cat              int32
dtype: object

In [13]:
newDF = df.filter(['Play_cat','PlayerLinenumber_cat','ActSceneLine_cat','Player_cat','PlayerLine_cat','NoOfWordsInPlayerLine' ], axis=1)

In [16]:
newDF.dtypes

Play_cat                  int8
PlayerLinenumber_cat     int16
ActSceneLine_cat         int16
Player_cat               int16
PlayerLine_cat           int32
NoOfWordsInPlayerLine    int64
dtype: object

In [14]:
X = newDF.ix[:,(0,1,2,4,5)].values
y = newDF.ix[:,3].values

C:\Users\p860n111\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
C:\Users\p860n111\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2, random_state=25)

In [17]:
from sklearn.linear_model import LogisticRegression
LogReg = LogisticRegression()
LogReg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [20]:
predictions = LogReg.predict(X_test)

In [22]:
#Use score method to get accuracy of model
score = LogReg.score(X_test,  y_test)
print(score)

0.041082211972802055

In [23]:
newDF.dtypes

Play_cat                  int8
PlayerLinenumber_cat     int16
ActSceneLine_cat         int16
Player_cat               int16
PlayerLine_cat           int32
NoOfWordsInPlayerLine    int64
dtype: object

In [33]:
X1 = newDF.ix[:,(0,1)].values
y1 = newDF.ix[:,3].values

C:\Users\p860n111\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
C:\Users\p860n111\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

In [34]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size = .3, random_state=25)

In [35]:
LogReg.fit(X_train1, y_train1)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [37]:
predictions = LogReg.predict(X_test1)

In [38]:
predictions

array([395, 361, 850, ..., 361, 361, 550], dtype=int16)

In [39]:
#Use score method to get accuracy of model
score = LogReg.score(X_test1,  y_test1)
print(score)

0.06067330247891967